package interfaces;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */



import classes.Renta;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;

/**
 *
 * @author rober
 */
public class input extends javax.swing.JFrame {

    /**
     * Creates new form input
     */
    ArrayList<Renta> lista;
    ArrayList<Double> bono;
    int previousIndex;

    public input() {
        initComponents();
        previousIndex = 0;
        lista = new ArrayList();
        bono = new ArrayList();
        llenarMonto();
        this.setLocationRelativeTo(null);
        this.jtxtnombre.setText("");
        this.jtxtsalario.setText("");
        this.jtxtafp.setText("");
        this.jtxtisss.setText("");
        this.jtstsalariomenos.setText("");
        this.jtxtrenta.setText("");
        this.jtxtsalarioneto.setText("");
        this.nit1.setText("");
        this.nit2.setText("");
        this.nit3.setText("");
        this.nit4.setText("");
        this.jtxtbono1.setText("");
        this.jtxtaguinaldo.setText("");
        this.setTitle("Calculo de salario en El Salvador");
        this.jButton2.setEnabled(false);
        this.jButton3.setEnabled(false);
        this.jtxtafp.setEditable(false);
        this.jtxtisss.setEditable(false);
        this.jtstsalariomenos.setEditable(false);
        this.jtxtrenta.setEditable(false);
        this.jtxtsalarioneto.setEditable(false);
        this.jRadioButton1.setEnabled(false);
        this.jRadioButton2.setEnabled(false);
        this.jRadioButton3.setEnabled(false);

        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd \n HH:mm");
        LocalDateTime now = LocalDateTime.now();
        this.jLabel7.setText(dtf.format(now));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jnombre = new javax.swing.JLabel();
        jsalario = new javax.swing.JLabel();
        jafp = new javax.swing.JLabel();
        jisss = new javax.swing.JLabel();
        jsalariomenos = new javax.swing.JLabel();
        jrenta = new javax.swing.JLabel();
        jsalarioneto = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jtxtnombre = new javax.swing.JTextField();
        jtxtsalario = new javax.swing.JTextField();
        jtxtafp = new javax.swing.JTextField();
        jtxtisss = new javax.swing.JTextField();
        jtstsalariomenos = new javax.swing.JTextField();
        jtxtrenta = new javax.swing.JTextField();
        jtxtsalarioneto = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtxtaguinaldo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtxtbono1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        nit1 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        nit2 = new javax.swing.JTextField();
        nit3 = new javax.swing.JTextField();
        nit4 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jnombre.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N
        jnombre.setText("Nombre:");

        jsalario.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N
        jsalario.setText("Ingresa tu salario:");

        jafp.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N
        jafp.setText("AFP:");

        jisss.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N
        jisss.setText("ISSS:");

        jsalariomenos.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N
        jsalariomenos.setText("Salario (-) ISSS y AFP:");

        jrenta.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N
        jrenta.setText("Renta (+) cuota fija:");

        jsalarioneto.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N
        jsalarioneto.setText("Salario neto:");

        jButton1.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        jButton1.setText("Borrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        jButton2.setText("Calcular");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        jButton3.setText("Renta Anual");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jtxtnombre.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jtxtnombre.setText("jTextField1");
        jtxtnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtnombreActionPerformed(evt);
            }
        });
        jtxtnombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtnombreKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtnombreKeyTyped(evt);
            }
        });

        jtxtsalario.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jtxtsalario.setText("jTextField2");
        jtxtsalario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtsalarioKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtsalarioKeyTyped(evt);
            }
        });

        jtxtafp.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jtxtafp.setText("jTextField3");

        jtxtisss.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jtxtisss.setText("jTextField4");

        jtstsalariomenos.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jtstsalariomenos.setText("jTextField5");

        jtxtrenta.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jtxtrenta.setText("jTextField6");

        jtxtsalarioneto.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jtxtsalarioneto.setText("jTextField7");

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButton1.setSelected(true);
        jRadioButton1.setText("Mensual");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButton2.setText("Quincenal");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButton3.setText("Semanal");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel1.setText("Tipo:");

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel2.setText("Ingresos extra:");

        jtxtaguinaldo.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jtxtaguinaldo.setText("jTextField8");

        jLabel3.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N
        jLabel3.setText("Aguinaldo:");

        jLabel4.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N
        jLabel4.setText("Bono:");

        jtxtbono1.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jtxtbono1.setText("jTextField9");
        jtxtbono1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtbono1ActionPerformed(evt);
            }
        });
        jtxtbono1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtbono1KeyTyped(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N
        jLabel5.setText("NIT:");

        nit1.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        nit1.setText("nit");
        nit1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nit1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nit1KeyTyped(evt);
            }
        });

        jComboBox1.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N
        jLabel6.setText("Mes:");

        jLabel7.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jLabel7.setText("fecha");

        nit2.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        nit2.setText("nit");
        nit2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nit2ActionPerformed(evt);
            }
        });
        nit2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nit2KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nit2KeyTyped(evt);
            }
        });

        nit3.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        nit3.setText("nit");
        nit3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nit3ActionPerformed(evt);
            }
        });
        nit3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nit3KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nit3KeyTyped(evt);
            }
        });

        nit4.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        nit4.setText("nit");
        nit4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nit4KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nit4KeyTyped(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("-");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("-");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("-");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(42, 42, 42)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jisss)
                                        .addComponent(jafp)
                                        .addComponent(jsalario)
                                        .addComponent(jnombre)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jrenta, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jsalarioneto, javax.swing.GroupLayout.Alignment.TRAILING))))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jsalariomenos)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtxtnombre, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                            .addComponent(jtxtsalario)
                            .addComponent(jtxtafp)
                            .addComponent(jtxtisss)
                            .addComponent(jtstsalariomenos)
                            .addComponent(jtxtrenta)
                            .addComponent(jtxtsalarioneto))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(94, 94, 94)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(72, 72, 72)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButton3)
                                    .addComponent(jRadioButton1)
                                    .addComponent(jRadioButton2)))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtxtbono1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(72, 72, 72)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jtxtaguinaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(7, 7, 7)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(nit1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(3, 3, 3)
                                        .addComponent(nit2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(3, 3, 3)
                                        .addComponent(nit3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(3, 3, 3)
                                        .addComponent(nit4, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(55, 55, 55))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jButton1)
                        .addGap(43, 43, 43)
                        .addComponent(jButton2)
                        .addGap(34, 34, 34)
                        .addComponent(jButton3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jnombre))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtxtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(nit1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nit2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nit3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nit4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtxtsalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jsalario)
                            .addComponent(jLabel2))
                        .addGap(26, 26, 26)
                        .addComponent(jafp))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtxtafp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)
                        .addComponent(jtxtbono1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jisss)
                    .addComponent(jtxtisss, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jtxtaguinaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtstsalariomenos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jsalariomenos))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtxtrenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jrenta))
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtxtsalarioneto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jsalarioneto))
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton3)
                        .addGap(2, 2, 2)
                        .addComponent(jRadioButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public String nit;
    public String nombre;
    public double aguinaldo;
    public boolean validar = false;

    public void llenarMonto() {
        for (int i = 0; i < 12; i++) {
            bono.add(Double.valueOf(0));
        }
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        borrar();
        this.jRadioButton1.setEnabled(false);
        this.jRadioButton2.setEnabled(false);
        this.jRadioButton3.setEnabled(false);
        this.jButton3.setEnabled(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    public void borrar() {
        this.jtxtsalario.setText("");
        this.jtxtafp.setText("");
        this.jtxtisss.setText("");
        this.jtstsalariomenos.setText("");
        this.jtxtrenta.setText("");
        this.jtxtsalarioneto.setText("");
        this.jtxtbono1.setText("");
    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        if (this.jtxtsalario.getText().isEmpty()) {
            borrar();
        } else {
            if (this.jtxtaguinaldo.getText().isEmpty()) {
                this.aguinaldo = 0;
            } else {
                this.aguinaldo = Double.parseDouble(this.jtxtaguinaldo.getText());
            }
            this.jButton3.setEnabled(true);
            this.jRadioButton1.setEnabled(true);
            this.jRadioButton2.setEnabled(true);
            this.jRadioButton3.setEnabled(true);

        }

        
        this.nombre = this.jtxtnombre.getText();
        

        mensual();
    }//GEN-LAST:event_jButton2ActionPerformed

    public double bono() {
        double bono;

        if (this.jtxtbono1.getText().isEmpty()) {
            bono = 0;
        } else {
            bono = Double.parseDouble(this.jtxtbono1.getText());
        }
        return bono;
    }
    private void jtxtnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtnombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtnombreActionPerformed

    private void jtxtsalarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtsalarioKeyTyped
        // TODO add your handling code here:
        char enter = evt.getKeyChar();
        if (!(Character.isDigit(enter))) {
            evt.consume();
        }
    }//GEN-LAST:event_jtxtsalarioKeyTyped

    private void jtxtnombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtnombreKeyTyped
        // TODO add your handling code here:
        char enter = evt.getKeyChar();
        if ((Character.isDigit(enter))) {
            evt.consume();
        }
    }//GEN-LAST:event_jtxtnombreKeyTyped

    private void jtxtnombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtnombreKeyReleased
        // TODO add your handling code here:
        if ((this.jtxtsalario.getText().length() < 3) && (this.jtxtnombre.getText() != null)) {
            this.jButton2.setEnabled(false);
        } else {
            this.validar = true;
            this.jButton2.setEnabled(true);
        }
    }//GEN-LAST:event_jtxtnombreKeyReleased

    private void jtxtsalarioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtsalarioKeyReleased
        // TODO add your handling code here:
        if ((this.jtxtsalario.getText().length() < 3) && (this.jtxtnombre.getText() != null)) {
            this.jButton2.setEnabled(false);
        } else {
            this.validar = true;
            this.jButton2.setEnabled(true);
        }
    }//GEN-LAST:event_jtxtsalarioKeyReleased

    public static double round(double value, int places) {
        if (places < 0) {
            throw new IllegalArgumentException();
        }

        long factor = (long) Math.pow(10, places);
        value = value * factor;
        long tmp = Math.round(value);
        return (double) tmp / factor;
    }

    public void mensual() {
        if (this.jtxtsalario.getText().isEmpty()) {
            borrar();
        } else {
            double salario, bono, afp, isss, isr, renta, mensual;
            renta = 0;
            salario = Double.parseDouble(this.jtxtsalario.getText());
            bono = round(bono(), 2);
            salario = round(salario + bono, 2);
            afp = round((salario * 0.0725), 2);
            if (salario > 1000) {
                isss = round((1000 * 0.03), 2);
            } else {
                isss = round((salario * 0.03), 2);
            }
            isr = round((salario - (afp + isss)), 2);

            if (isr <= 472) {//tramo 1
                renta = 0;
            } else if ((isr > 472) && (isr <= 895.24)) {//tramo 2
                renta = (isr - 472);
                renta = renta * 0.1;
                renta = round((renta + 17.67), 2);
            } else if ((isr > 895.24) && (isr <= 2038.10)) {//tramo 3
                renta = isr - 895.24;
                renta = renta * 0.2;
                renta = round((renta + 60), 2);
            } else if (isr > 2038.10) {//tramo 4
                renta = isr - 2038.10;
                renta = renta * 0.3;
                renta = round((renta + 288.57), 2);
            }
            mensual = round((salario - (afp + isss + renta)), 2);

            this.jtxtafp.setText("$" + Double.toString(afp));
            this.jtxtisss.setText("$" + Double.toString(isss));
            this.jtstsalariomenos.setText("$" + Double.toString(isr));
            this.jtxtrenta.setText("$" + Double.toString(renta));
            this.jtxtsalarioneto.setText("$" + Double.toString(mensual));
        }
    }
    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
        if (this.validar = true) {//mensual

            mensual();
        }

    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
        if (this.validar = true) {//quincenal
            if (this.jtxtsalario.getText().isEmpty()) {
                borrar();
            } else {
                double salario, bono, afp, isss, isr, renta, mensual;
                renta = 0;
                salario = Double.parseDouble(this.jtxtsalario.getText());
                bono = round(bono(), 2);
                salario = round((salario + bono), 2);
                afp = round((salario * 0.0725), 2);
                if (salario > 1000) {
                    isss = round((1000 * 0.03), 2);
                } else {
                    isss = salario * 0.03;
                }
                isr = round((salario - (afp + isss)), 2);

                if (isr <= 236) {//tramo 1
                    renta = 0;
                } else if ((isr > 236) && (isr <= 447.62)) {//tramo 2
                    renta = isr - 236;
                    renta = renta * 0.1;
                    renta = round((renta + 8.83), 2);
                } else if ((isr > 447.62) && (isr <= 1019.05)) {//tramo 3
                    renta = isr - 447.62;
                    renta = renta * 0.2;
                    renta = round((renta + 30), 2);
                } else if (isr > 1019.05) {//tramo 4
                    renta = isr - 1019.05;
                    renta = renta * 0.3;
                    renta = round((renta + 144.8), 2);
                }
                mensual = round((salario - (afp + isss + renta)), 2);

                this.jtxtafp.setText("$" + Double.toString(afp));
                this.jtxtisss.setText("$" + Double.toString(isss));
                this.jtstsalariomenos.setText("$" + Double.toString(isr));
                this.jtxtrenta.setText("$" + Double.toString(renta));
                this.jtxtsalarioneto.setText("$" + Double.toString(mensual));
            }
        }
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here
        if (this.validar = true) {//semanal
            if (this.jtxtsalario.getText().isEmpty()) {
                borrar();
            } else {
                double salario, bono, afp, isss, isr, renta, mensual;
                renta = 0;
                salario = Double.parseDouble(this.jtxtsalario.getText());
                bono = round(bono(), 2);
                salario = round((salario + bono), 2);
                afp = round((salario * 0.0725), 2);
                if (salario > 1000) {
                    isss = 1000 * 0.03;
                } else {
                    isss = round((salario * 0.03), 2);
                }
                isr = round((salario - (afp + isss)), 2);

                if (isr <= 118) {//tramo 1
                    renta = 0;
                } else if ((isr > 118) && (isr <= 223.81)) {//tramo 2
                    renta = isr - 118;
                    renta = renta * 0.1;
                    renta = round((renta + 4.42), 2);
                } else if ((isr > 223.81) && (isr <= 509.52)) {//tramo 3
                    renta = isr - 223.81;
                    renta = renta * 0.2;
                    renta = round((renta + 15), 2);
                } else if (isr > 509.52) {//tramo 4
                    renta = isr - 509.52;
                    renta = renta * 0.3;
                    renta = round((renta + 72.14), 2);
                }
                mensual = round((salario - (afp + isss + renta)), 2);

                this.jtxtafp.setText("$" + Double.toString(afp));
                this.jtxtisss.setText("$" + Double.toString(isss));
                this.jtstsalariomenos.setText("$" + Double.toString(isr));
                this.jtxtrenta.setText("$" + Double.toString(renta));
                this.jtxtsalarioneto.setText("$" + Double.toString(mensual));
            }
        }
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jtxtbono1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtbono1KeyTyped
        // TODO add your handling code here:
        char enter = evt.getKeyChar();
        if (!(Character.isDigit(enter))) {
            evt.consume();
        }
    }//GEN-LAST:event_jtxtbono1KeyTyped

    private void jtxtbono1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtbono1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtbono1ActionPerformed

    private void nit2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nit2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nit2ActionPerformed

    private void nit3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nit3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nit3ActionPerformed

    private void nit1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nit1KeyTyped
        // TODO add your handling code here:
        char enter = evt.getKeyChar();
        if (!(Character.isDigit(enter))) {
            evt.consume();
        }

        

    }//GEN-LAST:event_nit1KeyTyped

    private void nit1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nit1KeyReleased
        // TODO add your handling code here:
        if (this.nit1.getText().length() > 3) {
            this.nit2.requestFocus();
        }
    }//GEN-LAST:event_nit1KeyReleased

    private void nit2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nit2KeyReleased
        // TODO add your handling code here:
        if (this.nit2.getText().length() > 5) {
            this.nit3.requestFocus();
        }
    }//GEN-LAST:event_nit2KeyReleased

    private void nit3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nit3KeyReleased
        // TODO add your handling code here:
        if (this.nit3.getText().length() > 2) {
            this.nit4.requestFocus();
        }
    }//GEN-LAST:event_nit3KeyReleased

    public int contador = 0;
    public double aguinaldo_renta = 0;
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        contador++;
        if (this.jtxtsalario.getText().isEmpty()) {
            borrar();
        } else {

            this.nit = this.nit1.getText() + "-" + this.nit2.getText() + "-" + this.nit3.getText() + "-" + this.nit4.getText();
            this.nombre = this.jtxtnombre.getText();
            if (this.jtxtaguinaldo.getText().isEmpty()) {
                this.aguinaldo = 0;
            } else {
                this.aguinaldo = Double.parseDouble(this.jtxtaguinaldo.getText());
                if(this.aguinaldo > 600){
                    aguinaldo_renta = this.aguinaldo - 600;
                }
            }
            for (int i = 0; i < 11; i++) {
                this.lista.add(new Renta(round(Double.parseDouble(this.jtxtsalario.getText()), 2), round(bono(), 2)));
            }
            this.lista.add(new Renta(round(Double.parseDouble(this.jtxtsalario.getText()) + aguinaldo_renta, 2), round(bono(), 2)));
            System.out.println("afp: " + this.lista.get(0).afp + "\n isss: " + this.lista.get(0).isss + "\n isr: " + this.lista.get(0).salariomenos
                    + "\n renta: " + this.lista.get(0).renta + "\n neto: " + this.lista.get(0).salarionetom);
            
            this.nit = this.nit1.getText() + "-" + this.nit2.getText() + "-" + this.nit3.getText() + "-" + this.nit4.getText();
            tabla tabla = new tabla(this.lista, this.aguinaldo, aguinaldo_renta, this.nit);
            tabla.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jButton3ActionPerformed
    public int c = 0;
    public int a = 0;
    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        // TODO add your handling code here: c++;
        c++;
        if (c % 2 == 0) {
            a++;
            this.bono.set(WIDTH, aguinaldo);
            System.out.println(this.jComboBox1.getSelectedIndex());
        }
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        System.out.println(this.jComboBox1.getSelectedIndex());
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void nit4KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nit4KeyReleased
        // TODO add your handling code here:
        if (this.nit4.getText().length() > 0) {
            this.requestFocus();
        }
        
    }//GEN-LAST:event_nit4KeyReleased

    private void nit2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nit2KeyTyped
        // TODO add your handling code here:
        char enter = evt.getKeyChar();
        if (!(Character.isDigit(enter))) {
            evt.consume();
        }
    }//GEN-LAST:event_nit2KeyTyped

    private void nit3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nit3KeyTyped
        // TODO add your handling code here:
        char enter = evt.getKeyChar();
        if (!(Character.isDigit(enter))) {
            evt.consume();
        }
    }//GEN-LAST:event_nit3KeyTyped

    private void nit4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nit4KeyTyped
        // TODO add your handling code here:
        char enter = evt.getKeyChar();
        if (!(Character.isDigit(enter))) {
            evt.consume();
        }
    }//GEN-LAST:event_nit4KeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(input.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(input.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(input.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(input.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new input().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JLabel jafp;
    private javax.swing.JLabel jisss;
    private javax.swing.JLabel jnombre;
    private javax.swing.JLabel jrenta;
    private javax.swing.JLabel jsalario;
    private javax.swing.JLabel jsalariomenos;
    private javax.swing.JLabel jsalarioneto;
    private javax.swing.JTextField jtstsalariomenos;
    private javax.swing.JTextField jtxtafp;
    private javax.swing.JTextField jtxtaguinaldo;
    private javax.swing.JTextField jtxtbono1;
    private javax.swing.JTextField jtxtisss;
    private javax.swing.JTextField jtxtnombre;
    private javax.swing.JTextField jtxtrenta;
    private javax.swing.JTextField jtxtsalario;
    private javax.swing.JTextField jtxtsalarioneto;
    private javax.swing.JTextField nit1;
    private javax.swing.JTextField nit2;
    private javax.swing.JTextField nit3;
    private javax.swing.JTextField nit4;
    // End of variables declaration//GEN-END:variables
}
